# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

steps:
  - script: |
      set -ex
      sudo apt install qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virtinst libvirt-daemon
      sudo systemctl enable --now libvirtd
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker run --rm -t arm64v8/ubuntu uname -m
    displayName: "Try"
