# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: linux-amd64-pkg
      path: $(system.defaultWorkingDirectory)/dist/pkg
      source: "specific"
      project: "release"
      pipeline: 22
      runVersion: "specific"
      buildId: 3678
